name: CI pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Lint (reglas de estilo)
        run: npm run lint
      
      - name: Build (opcional)
        run: npm run build

      #- name: Correr tests
      #        run: npm test

      - name: Deploy en Render
        if: success()
        run: curl -X POST https://api.render.com/deploy/srv-d17n7kodl3ps738uit5g?key=ne0yX-MR30g
